-- Procedure normalized version UUIDs are regenerated by its current store.
-- Capture the content, not just that transient UUID, before an asynchronous start.
ALTER TABLE hrm_schema.procedure_links ADD COLUMN IF NOT EXISTS definition_snapshot jsonb;
DO $$ BEGIN
  IF to_regclass('procedure_schema.versions') IS NOT NULL THEN
    UPDATE hrm_schema.procedure_links l SET definition_snapshot=v.snapshot
    FROM procedure_schema.definitions d JOIN procedure_schema.versions v ON v.id=d.current_version_id
    WHERE l.definition_id=d.id AND l.definition_snapshot IS NULL AND l.instance_id IS NULL;
  END IF;
END $$;
