FROM nginx:1.29-alpine

COPY infrastructure/nginx/nginx.docker.conf /etc/nginx/nginx.conf
COPY infrastructure/nginx/procedure-maintenance.html /usr/share/nginx/html/procedure-maintenance.html
COPY infrastructure/nginx/maintenance-maintenance.html /usr/share/nginx/html/maintenance-maintenance.html
