import { randomUUID } from 'node:crypto';
import { PostgresPoolRegistry, inTransaction } from '@enterprise-platform/adapter-database';
import type { TenantDatabaseReference } from '@enterprise-platform/contracts-tenancy';
import type { AssetSummaryDto,CreateAssetDto,CreateItemDto,CreateWarehouseDto,ExportStockDto,ImportStockDto,InventoryWorkspaceDto,ItemDetailDto,ReservationSummaryDto,SerialTrackingDto,StockBalanceDto,StockTransactionDto,UpdateAssetSpecsDto,UploadAssetDocumentDto,WarehouseSummaryDto } from '@enterprise-platform/contract-inventory';
import { InventoryError } from '../domain/inventory.error.js';
import { assertCanIssue } from '../domain/stock.policy.js';
import type { InventoryStore } from '../application/inventory-store.port.js';
type Row=Record<string,unknown>;
export class PostgresInventoryStore implements InventoryStore {
 constructor(private readonly pools:PostgresPoolRegistry,private readonly resolve:(tenantId:string)=>Promise<TenantDatabaseReference>){}
 async workspace(tenantId:string):Promise<InventoryWorkspaceDto>{ const pool=await this.pools.forTenant(await this.resolve(tenantId)); const [w,i,b,t,a,s,r]=await Promise.all([
  pool.query<Row>(`SELECT w.*,coalesce(stock.item_count,0)::int item_count,coalesce(loc.location_count,0)::int location_count,coalesce(stock.total_on_hand,0) total_on_hand FROM inventory_schema.warehouses w LEFT JOIN LATERAL (SELECT count(DISTINCT item_id) item_count,sum(on_hand_qty) total_on_hand FROM inventory_schema.stock_balances WHERE warehouse_id=w.id) stock ON true LEFT JOIN LATERAL (SELECT count(*) location_count FROM inventory_schema.warehouse_locations WHERE warehouse_id=w.id) loc ON true ORDER BY w.plant_code NULLS LAST,w.code`),
  pool.query<Row>(`SELECT i.*,m.category,m.manufacturer,m.reorder_point,u.name uom FROM inventory_schema.items i JOIN inventory_schema.uoms u ON u.id=i.uom_id LEFT JOIN amm_schema.amm_materials m ON m.id=i.id ORDER BY i.code`),
  pool.query<Row>(`SELECT b.*,w.code warehouse_code,i.code item_code,i.name item_name,i.min_stock,u.name uom FROM inventory_schema.stock_balances b JOIN inventory_schema.warehouses w ON w.id=b.warehouse_id JOIN inventory_schema.items i ON i.id=b.item_id JOIN inventory_schema.uoms u ON u.id=i.uom_id ORDER BY i.code,w.code`),
  pool.query<Row>(`SELECT t.*,i.code item_code,i.name item_name,w.code warehouse_code FROM inventory_schema.stock_transactions t JOIN inventory_schema.items i ON i.id=t.item_id JOIN inventory_schema.warehouses w ON w.id=t.warehouse_id ORDER BY t.transaction_date DESC LIMIT 100`),
  pool.query<Row>(`SELECT a.*,count(b.id)::int bom_count,coalesce(jsonb_agg(jsonb_build_object('itemCode',m.code,'itemName',m.name,'quantity',b.standard_quantity,'critical',b.is_critical_spare)) FILTER (WHERE b.id IS NOT NULL),'[]'::jsonb) bom,
    coalesce((SELECT jsonb_agg(event ORDER BY event_date DESC) FROM (
      SELECT jsonb_build_object('id',l.id,'date',l.created_at,'title',concat(l.from_status,' → ',l.to_status),'type',CASE WHEN l.to_status='MAINTENANCE' THEN 'PREVENTIVE' ELSE 'INSPECTION' END,'status','COMPLETED','technician',l.changed_by::text,'note',l.reason) event,l.created_at event_date FROM amm_schema.amm_asset_status_logs l WHERE l.asset_id=a.id
      UNION ALL
      SELECT jsonb_build_object('id',ins.id,'date',ins.installed_at,'title',concat(CASE ins.action WHEN 'INSTALL' THEN 'Lắp đặt ' WHEN 'REMOVE' THEN 'Tháo dỡ ' ELSE 'Thay thế ' END,mat.name),'type','CORRECTIVE','status','COMPLETED','technician',ins.technician_id::text,'note',ins.note,'replacedParts',jsonb_build_array(mat.code)) event,ins.installed_at event_date FROM amm_schema.amm_asset_installations ins JOIN amm_schema.amm_materials mat ON mat.id=ins.material_id WHERE ins.asset_id=a.id
    ) events),'[]'::jsonb) maintenance_history,
    coalesce((SELECT jsonb_agg(jsonb_build_object('id',concat('material-',pm.id),'title',concat('Quy trình thay thế ',pm.name),'frequency','Theo kế hoạch bảo trì','estimatedDuration',concat(coalesce((SELECT sum(coalesce((step->>'durationMinutes')::int,0)) FROM jsonb_array_elements(pm.replacement_steps) step),0),' phút'),'steps',(SELECT jsonb_agg(jsonb_build_object('stepNo',coalesce((step->>'order')::int,ordinality::int),'title',coalesce(step->>'title','Bước thực hiện'),'description',coalesce(step->>'note',step->>'title',''),'toolRequired',array_to_string(ARRAY(SELECT jsonb_array_elements_text(coalesce(step->'requiredTools','[]'::jsonb))),', ')) ORDER BY ordinality) FROM jsonb_array_elements(pm.replacement_steps) WITH ORDINALITY AS steps(step,ordinality)))) FROM amm_schema.amm_asset_boms pb JOIN amm_schema.amm_materials pm ON pm.id=pb.material_id WHERE pb.asset_id=a.id AND jsonb_typeof(pm.replacement_steps)='array' AND jsonb_array_length(pm.replacement_steps)>0),'[]'::jsonb) procedures
    FROM amm_schema.amm_assets a LEFT JOIN amm_schema.amm_asset_boms b ON b.asset_id=a.id LEFT JOIN amm_schema.amm_materials m ON m.id=b.material_id GROUP BY a.id ORDER BY CASE a.type WHEN 'PLANT' THEN 1 WHEN 'SYSTEM' THEN 2 WHEN 'EQUIPMENT' THEN 3 ELSE 4 END,a.code`),
  pool.query<Row>(`SELECT s.*,m.code item_code,m.name item_name,w.code warehouse_code,a.code asset_code FROM amm_schema.amm_serial_tracking s JOIN amm_schema.amm_materials m ON m.id=s.material_id LEFT JOIN amm_schema.amm_warehouses w ON w.id=s.current_warehouse_id LEFT JOIN amm_schema.amm_assets a ON a.id=s.current_asset_id ORDER BY m.code,s.serial_number`),
  pool.query<Row>(`SELECT r.*,count(i.id)::int line_count,coalesce(sum(i.quantity_reserved),0) total_reserved FROM amm_schema.amm_reservations r LEFT JOIN amm_schema.amm_reservation_items i ON i.reservation_id=r.id GROUP BY r.id ORDER BY r.created_at DESC`)]);
  const balances=b.rows.map(balance); return {warehouses:w.rows.map(warehouse),items:i.rows.map(item),balances,lowStock:balances.filter(x=>x.available<=x.minStock),transactions:t.rows.map(transaction),assets:a.rows.map(asset),serials:s.rows.map(serial),reservations:r.rows.map(reservation)}; }
 async createWarehouse(tenantId:string,input:CreateWarehouseDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId)); try { const r=await pool.query<Row>(`INSERT INTO inventory_schema.warehouses(code,name,type,address) VALUES($1,$2,$3,$4) RETURNING *,0::int item_count,0::numeric total_on_hand`,[input.code.trim().toUpperCase(),input.name.trim(),input.type??'PHYSICAL',input.address?.trim()||null]); return warehouse(r.rows[0]); } catch(e){ this.db(e,'Mã kho đã tồn tại.'); } }
 async createItem(tenantId:string,input:CreateItemDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId)); try { const r=await pool.query<Row>(`INSERT INTO inventory_schema.items(code,name,uom_id,tracking_type,costing_method,min_stock,max_stock) SELECT $1,$2,id,$4,$5,$6,$7 FROM inventory_schema.uoms WHERE code=$3 RETURNING *, $3::text uom`,[input.code.trim().toUpperCase(),input.name.trim(),input.uomCode.trim().toUpperCase(),input.trackingType??'NONE',input.costingMethod??'FIFO',input.minStock??0,input.maxStock??0]); if(!r.rows[0]) throw new InventoryError('not_found','Không tìm thấy đơn vị tính.'); return item(r.rows[0]); } catch(e){ if(e instanceof InventoryError)throw e; this.db(e,'Mã vật tư đã tồn tại.'); } }
 async createAsset(tenantId:string,input:CreateAssetDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId)); try { return await inTransaction(pool,async c=>{let parentType:string|undefined;if(input.parentId){const p=await c.query<Row>(`SELECT type FROM amm_schema.amm_assets WHERE id=$1 FOR SHARE`,[input.parentId]);if(!p.rows[0])throw new InventoryError('not_found','Không tìm thấy tài sản cha.');parentType=str(p.rows[0].type);}assertAssetParent(parentType,input.type);const code=input.code.trim().toUpperCase();const r=await c.query<Row>(`INSERT INTO amm_schema.amm_assets(code,name,parent_id,type,criticality,serial_number,specs,qr_code) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8) RETURNING *`,[code,input.name.trim(),input.parentId??null,input.type,input.criticality??'MEDIUM',input.serialNumber?.trim()||null,JSON.stringify(input.specs??{}),`QR-${code}`]);return asset(r.rows[0]);});}catch(e){if(e instanceof InventoryError)throw e;this.db(e,'Mã thiết bị đã tồn tại.');} }
 async updateAssetSpecs(tenantId:string,userId:string,assetId:string,input:UpdateAssetSpecsDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId));return inTransaction(pool,async c=>{const current=await c.query<Row>(`SELECT status FROM amm_schema.amm_assets WHERE id=$1 FOR UPDATE`,[assetId]);if(!current.rows[0])throw new InventoryError('not_found','Không tìm thấy thiết bị.');const oldStatus=str(current.rows[0].status);const r=await c.query<Row>(`UPDATE amm_schema.amm_assets SET specs=$2::jsonb || CASE WHEN specs ? '_documents' THEN jsonb_build_object('_documents',specs->'_documents') ELSE '{}'::jsonb END || CASE WHEN $3::text IS NOT NULL THEN jsonb_build_object('_description',$3::text) ELSE '{}'::jsonb END,status=coalesce($4,status),criticality=coalesce($5,criticality),updated_at=now() WHERE id=$1 RETURNING *`,[assetId,JSON.stringify(input.specs??{}),input.description??null,input.status??null,input.criticality??null]);if(input.status&&input.status!==oldStatus)await c.query(`INSERT INTO amm_schema.amm_asset_status_logs(asset_id,from_status,to_status,reason,changed_by) VALUES($1,$2,$3,$4,$5)`,[assetId,oldStatus,input.status,input.description??'Cập nhật từ hồ sơ tài sản',userId]);return asset(r.rows[0]);}); }
 async uploadAssetDocument(tenantId:string,assetId:string,input:UploadAssetDocumentDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId));const document={id:randomUUID(),title:input.title.trim(),docType:input.docType,fileName:input.fileName.trim(),fileUrl:input.fileUrl.trim(),fileSize:input.fileSize,uploadedAt:new Date().toISOString()};const r=await pool.query(`UPDATE amm_schema.amm_assets SET specs=jsonb_set(coalesce(specs,'{}'::jsonb),'{_documents}',coalesce(specs->'_documents','[]'::jsonb) || $2::jsonb,true),updated_at=now() WHERE id=$1 RETURNING id`,[assetId,JSON.stringify(document)]);if(!r.rowCount)throw new InventoryError('not_found','Không tìm thấy thiết bị.');return document; }
 async importStock(tenantId:string,userId:string,input:ImportStockDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId)); return inTransaction(pool,async c=>{ const id=randomUUID(); await c.query(`INSERT INTO inventory_schema.stock_receipts(id,receipt_no,warehouse_id,supplier_code,created_by) VALUES($1,$2,$3,$4,$5)`,[id,input.receiptNo,input.warehouseId,input.supplierCode??null,userId]); for(const line of input.lines){ const locked=await c.query<Row>(`INSERT INTO inventory_schema.stock_balances(warehouse_id,location_id,item_id,lot_id) VALUES($1,$2,$3,$4) ON CONFLICT (warehouse_id,location_id,item_id,lot_id) DO UPDATE SET updated_at=now() RETURNING *`,[input.warehouseId,line.locationId??null,line.itemId,line.lotId??null]); const before=Number(locked.rows[0]?.on_hand_qty??0),after=before+line.quantity; await c.query(`UPDATE inventory_schema.stock_balances SET on_hand_qty=$2,updated_at=now() WHERE id=$1`,[locked.rows[0]?.id,after]); await c.query(`INSERT INTO inventory_schema.stock_receipt_items(receipt_id,item_id,location_id,lot_id,quantity,unit_cost) VALUES($1,$2,$3,$4,$5,$6)`,[id,line.itemId,line.locationId??null,line.lotId??null,line.quantity,line.unitCost??0]); await this.ledger(c,'RECEIPT',line.quantity,before,after,input.receiptNo,id,input.warehouseId,line,userId); } return{id,receiptNo:input.receiptNo}; }); }
 async exportStock(tenantId:string,userId:string,input:ExportStockDto){ const pool=await this.pools.forTenant(await this.resolve(tenantId)); return inTransaction(pool,async c=>{ const id=randomUUID(); await c.query(`INSERT INTO inventory_schema.stock_issues(id,issue_no,warehouse_id,reference_type,reference_id,created_by) VALUES($1,$2,$3,$4,$5,$6)`,[id,input.issueNo,input.warehouseId,input.referenceType??null,input.referenceId??null,userId]); for(const line of input.lines){ const r=await c.query<Row>(`SELECT * FROM inventory_schema.stock_balances WHERE warehouse_id=$1 AND item_id=$2 AND location_id IS NOT DISTINCT FROM $3 AND lot_id IS NOT DISTINCT FROM $4 FOR UPDATE`,[input.warehouseId,line.itemId,line.locationId??null,line.lotId??null]); if(!r.rows[0]) throw new InventoryError('insufficient_stock','Không có tồn kho phù hợp để xuất.'); const before=Number(r.rows[0].on_hand_qty),available=Number(r.rows[0].available_qty); assertCanIssue(available,line.quantity); const after=before-line.quantity; await c.query(`UPDATE inventory_schema.stock_balances SET on_hand_qty=$2,updated_at=now() WHERE id=$1`,[r.rows[0].id,after]); await c.query(`INSERT INTO inventory_schema.stock_issue_items(issue_id,item_id,location_id,lot_id,quantity,unit_cost) VALUES($1,$2,$3,$4,$5,$6)`,[id,line.itemId,line.locationId??null,line.lotId??null,line.quantity,line.unitCost??0]); await this.ledger(c,'ISSUE',-line.quantity,before,after,input.issueNo,id,input.warehouseId,line,userId); } return{id,issueNo:input.issueNo}; }); }
 private ledger(c:{query:(q:string,v?:unknown[])=>Promise<unknown>},type:string,change:number,before:number,after:number,no:string,id:string,wid:string,line:{itemId:string;locationId?:string;lotId?:string;unitCost?:number},user:string){ return c.query(`INSERT INTO inventory_schema.stock_transactions(transaction_code,transaction_type,item_id,warehouse_id,location_id,lot_id,qty_change,balance_before,balance_after,unit_cost,reference_type,reference_id,performed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[`${no}-${line.itemId}-${randomUUID().slice(0,8)}`,type,line.itemId,wid,line.locationId??null,line.lotId??null,change,before,after,line.unitCost??0,type,id,user]); }
 private db(e:unknown,msg:string):never { if(typeof e==='object'&&e&&'code' in e&&String(e.code)==='23505')throw new InventoryError('conflict',msg); throw e; }
}
const str=(v:unknown)=>String(v); const num=(v:unknown)=>Number(v);
function warehouse(r?:Row):WarehouseSummaryDto{if(!r)throw new InventoryError('conflict','Không nhận được dữ liệu kho.');return{id:str(r.id),code:str(r.code),name:str(r.name),type:str(r.type),plantCode:optional(r.plant_code),warehouseType:optional(r.warehouse_type),address:optional(r.address),itemCount:num(r.item_count),locationCount:num(r.location_count),totalOnHand:num(r.total_on_hand)};}
function item(r?:Row):ItemDetailDto{if(!r)throw new InventoryError('conflict','Không nhận được dữ liệu vật tư.');return{id:str(r.id),code:str(r.code),name:str(r.name),uom:str(r.uom),category:optional(r.category),manufacturer:optional(r.manufacturer),trackingType:r.tracking_type as ItemDetailDto['trackingType'],minStock:num(r.min_stock),maxStock:num(r.max_stock),reorderPoint:r.reorder_point==null?undefined:num(r.reorder_point),isActive:Boolean(r.is_active)};}
function balance(r:Row):StockBalanceDto{return{warehouseId:str(r.warehouse_id),warehouseCode:str(r.warehouse_code),itemId:str(r.item_id),itemCode:str(r.item_code),itemName:str(r.item_name),uom:str(r.uom),onHand:num(r.on_hand_qty),reserved:num(r.reserved_qty),available:num(r.available_qty),minStock:num(r.min_stock)};}
function transaction(r:Row):StockTransactionDto{return{id:str(r.id),code:str(r.transaction_code),date:new Date(str(r.transaction_date)).toISOString(),type:str(r.transaction_type),itemCode:str(r.item_code),itemName:str(r.item_name),warehouseCode:str(r.warehouse_code),quantity:num(r.qty_change),balanceBefore:num(r.balance_before),balanceAfter:num(r.balance_after),unitCost:num(r.unit_cost),referenceType:str(r.reference_type),referenceId:str(r.reference_id),notes:optional(r.notes)};}
function asset(r:Row):AssetSummaryDto{
  const code = str(r.code);
  const rawSpecs=isRecord(r.specs)?r.specs:{};
  const specs=Object.fromEntries(Object.entries(rawSpecs).filter(([key])=>!key.startsWith('_')));
  return{id:str(r.id),code,name:str(r.name),parentId:optional(r.parent_id),type:r.type as AssetSummaryDto['type'],status:str(r.status),criticality:str(r.criticality),serialNumber:optional(r.serial_number),qrCode:optional(r.qr_code),specs,bomCount:num(r.bom_count??0),bom:Array.isArray(r.bom)?r.bom as AssetSummaryDto['bom']:[],documents:Array.isArray(rawSpecs._documents)?rawSpecs._documents as AssetSummaryDto['documents']:[],maintenanceHistory:Array.isArray(r.maintenance_history)?r.maintenance_history as AssetSummaryDto['maintenanceHistory']:[],procedures:Array.isArray(r.procedures)?r.procedures as AssetSummaryDto['procedures']:[]};
}
function serial(r:Row):SerialTrackingDto{return{id:str(r.id),itemCode:str(r.item_code),itemName:str(r.item_name),serialNumber:str(r.serial_number),internalCode:optional(r.internal_code),status:str(r.current_status),locationType:str(r.location_type),warehouseCode:optional(r.warehouse_code),assetCode:optional(r.asset_code)};}
function reservation(r:Row):ReservationSummaryDto{return{id:str(r.id),code:str(r.reservation_code),referenceType:str(r.reference_type),referenceId:str(r.reference_id),status:str(r.status),expiresAt:r.expires_at?new Date(str(r.expires_at)).toISOString():undefined,lineCount:num(r.line_count),totalReserved:num(r.total_reserved)};}
function optional(v:unknown):string|undefined{return v==null?undefined:String(v);}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
function assertAssetParent(parentType:string|undefined,childType:CreateAssetDto['type']){const valid=!parentType?childType==='PLANT':parentType==='PLANT'?childType==='SYSTEM':parentType==='SYSTEM'?childType==='EQUIPMENT':parentType==='EQUIPMENT'||parentType==='COMPONENT'?childType==='COMPONENT':false;if(!valid)throw new InventoryError('validation','Cấp tài sản không đúng cấu trúc PLANT → SYSTEM → EQUIPMENT → COMPONENT.');}
