export const REALTIME_PLATFORM_POOL = Symbol('REALTIME_PLATFORM_POOL');
export const REALTIME_TENANT_POOLS = Symbol('REALTIME_TENANT_POOLS');
export const REALTIME_REDIS_CLIENT = Symbol('REALTIME_REDIS_CLIENT');
export const REALTIME_AUTH_CLIENT = Symbol('REALTIME_AUTH_CLIENT');
export const REALTIME_STORE_REGISTRY = Symbol('REALTIME_STORE_REGISTRY');
export const REALTIME_REQUEST_CONTEXTS = Symbol('REALTIME_REQUEST_CONTEXTS');
