'use client';

import type { CreateTenantRequest, CreateTenantResponse } from '@enterprise-platform/contracts-tenancy';
import { ArrowLeft, ArrowRight, Building2, Check, CircleCheck, Database, Lock, PackageCheck, ServerCog, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';

type WizardStep = 'step-1' | 'step-2' | 'step-3' | 'step-4' | 'progress';
type ProvisionState = 'idle' | 'provisioning' | 'completed' | 'failed';
type Draft = { name: string; slug: string; adminName: string; adminEmail: string; password: string; confirmation: string; plan: string; modules: string[]; databaseName: string; secretRef: string; host: string; port: string; provisionState: ProvisionState; error?: string; tenantName?: string };
type Props = { draft: Draft; update: (patch: Partial<Draft>) => void };
const DRAFT_KEY = 'platform:create-tenant-draft:v1';
const defaults: Draft = { name: '', slug: '', adminName: '', adminEmail: '', password: '', confirmation: '', plan: 'Enterprise', modules: ['crm', 'procedure-engine'], databaseName: '', secretRef: '', host: 'localhost', port: '55436', provisionState: 'idle' };
const steps = [{ key: 'step-1', label: 'Doanh nghiệp' }, { key: 'step-2', label: 'Quản trị viên' }, { key: 'step-3', label: 'Gói & Module' }, { key: 'step-4', label: 'Database' }] as const;

function csrfToken() { const value = document.cookie.split('; ').find((item) => item.startsWith('ep_csrf='))?.split('=').slice(1).join('='); return value ? decodeURIComponent(value) : ''; }
function slugify(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
function loadDraft(): Draft { try { return { ...defaults, ...JSON.parse(sessionStorage.getItem(DRAFT_KEY) ?? '{}') }; } catch { return defaults; } }
function saveDraft(draft: Draft) { sessionStorage.setItem(DRAFT_KEY, JSON.stringify(draft)); }
function apiMessage(payload: { message?: string | string[] }) { return Array.isArray(payload.message) ? payload.message.join(' ') : (payload.message ?? 'Không thể khởi tạo tenant.'); }

export function CreateTenantWizard({ step, actor }: { step: string; actor: string }) {
  const [draft, setDraft] = useState<Draft>(defaults);
  const [ready, setReady] = useState(false);
  useEffect(() => { setDraft(loadDraft()); setReady(true); }, []);
  function update(patch: Partial<Draft>) { setDraft((current) => { const next = { ...current, ...patch }; saveDraft(next); return next; }); }
  if (!ready) return null;
  const titles: Record<WizardStep, [string, string]> = { 'step-1': ['Tạo Tenant mới', 'Khởi tạo doanh nghiệp, tài khoản quản trị, module và Dedicated Database.'], 'step-2': ['Tenant Admin', 'Thiết lập tài khoản quản trị đầu tiên cho doanh nghiệp.'], 'step-3': ['Gói dịch vụ & Module', 'Chọn gói subscription và các module sẽ được cấp cho tenant.'], 'step-4': ['Database & xác nhận', 'Kiểm tra Dedicated Database trước khi hoàn tất tạo tenant.'], progress: ['Đang khởi tạo Tenant', 'Hệ thống đang provision các tài nguyên cần thiết.'] };
  const [title, subtitle] = titles[step as WizardStep];
  const current = step === 'progress' ? 4 : Number(step.at(-1));
  return <div className="min-h-screen bg-[#f8f9ff] text-slate-900"><aside className="fixed inset-y-0 left-0 hidden w-60 bg-[#091426] px-4 py-6 text-white lg:block"><p className="font-semibold">SaaS Platform</p><p className="mt-1 text-xs text-slate-400">Quản trị hệ thống</p></aside><div className="lg:pl-60"><header className="flex h-16 items-center border-b bg-white px-4 lg:px-8"><Link className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-[#091426]" href="/platform/tenants"><ArrowLeft className="size-4" />Quản lý Tenant</Link><span className="ml-auto text-sm text-muted-foreground">{actor}</span></header><main className="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8"><div className="mb-8"><h1 className="text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p></div>{step !== 'progress' ? <Stepper current={current} /> : null}<div className="mt-10">{step === 'step-1' && <CompanyStep draft={draft} update={update} />}{step === 'step-2' && <AdminStep draft={draft} update={update} />}{step === 'step-3' && <PlanStep draft={draft} update={update} />}{step === 'step-4' && <DatabaseStep draft={draft} update={update} />}{step === 'progress' && <ProvisioningStep draft={draft} update={update} />}</div></main></div></div>;
}

function Stepper({ current }: { current: number }) { return <ol className="grid grid-cols-4 gap-2" aria-label="Tiến trình tạo tenant">{steps.map((item, index) => { const n = index + 1; const active = n === current; const done = n < current; return <li className="flex flex-col items-center gap-2 text-center" key={item.key}><span className={cn('grid size-8 place-items-center rounded-full border text-xs font-semibold', active || done ? 'border-[#091426] bg-[#091426] text-white' : 'border-slate-300 bg-white text-slate-500')}>{done ? <Check className="size-4" /> : n}</span><span className={cn('text-xs font-medium', active ? 'text-[#091426]' : 'text-slate-500')}>{item.label}</span></li>; })}</ol>; }

function CompanyStep({ draft, update }: Props) { const next = () => { if (!draft.name || !draft.slug) return update({ error: 'Vui lòng nhập tên doanh nghiệp và mã tenant.' }); update({ error: undefined }); location.assign('/platform/tenants/create/step-2'); }; return <WizardCard icon={Building2} title="Thông tin doanh nghiệp" description="Thiết lập định danh cơ bản cho tenant."><div className="grid gap-5 sm:grid-cols-2"><Field label="Tên doanh nghiệp"><Input onChange={(event) => { const name = event.currentTarget.value; const slug = slugify(name); update({ name, slug, databaseName: slug.replaceAll('-', '_'), secretRef: slug ? `TENANT_${slug.replaceAll('-', '_').toUpperCase()}_DATABASE_URL` : '' }); }} value={draft.name} /></Field><Field label="Mã tenant"><Input onChange={(event) => update({ slug: event.currentTarget.value })} value={draft.slug} /></Field></div><WizardError message={draft.error} /><Footer onNext={next} /></WizardCard>; }
function AdminStep({ draft, update }: Props) { const next = () => { if (!draft.adminName || !draft.adminEmail || draft.password.length < 12) return update({ error: 'Nhập tên, email và mật khẩu tối thiểu 12 ký tự.' }); if (draft.password !== draft.confirmation) return update({ error: 'Xác nhận mật khẩu chưa khớp.' }); update({ error: undefined }); location.assign('/platform/tenants/create/step-3'); }; return <WizardCard icon={ShieldCheck} title="Quản trị viên Tenant" description="Tài khoản này có quyền tenant-admin sau khi tenant được khởi tạo."><div className="grid gap-5 sm:grid-cols-2"><Field label="Họ và tên"><Input onChange={(event) => update({ adminName: event.currentTarget.value })} value={draft.adminName} /></Field><Field label="Email công việc"><Input onChange={(event) => update({ adminEmail: event.currentTarget.value })} type="email" value={draft.adminEmail} /></Field><Field label="Mật khẩu tạm thời"><Input autoComplete="new-password" onChange={(event) => update({ password: event.currentTarget.value })} type="password" value={draft.password} /></Field><Field label="Xác nhận mật khẩu"><Input autoComplete="new-password" onChange={(event) => update({ confirmation: event.currentTarget.value })} type="password" value={draft.confirmation} /></Field></div><div className="mt-5 flex gap-3 rounded-lg border border-sky-200 bg-sky-50 p-3 text-sm text-sky-900"><CircleCheck className="size-4 shrink-0" />Hệ thống tạo tài khoản ngay khi provisioning hoàn tất; chưa gửi email tự động.</div><WizardError message={draft.error} /><Footer back="/platform/tenants/create/step-1" onNext={next} /></WizardCard>; }
function PlanStep({ draft, update }: Props) { const modules = [{ key: 'crm', name: 'CRM' }, { key: 'procedure-engine', name: 'Procedure Engine' }, { key: 'maintenance', name: 'Maintenance' }]; return <div className="space-y-6"><WizardCard icon={PackageCheck} title="Gói dịch vụ" description="Thông tin gói được lưu trong wizard."><div className="grid gap-3 sm:grid-cols-3">{['Starter', 'Professional', 'Enterprise'].map((plan) => <label className={cn('rounded-xl border p-4', draft.plan === plan && 'border-[#091426] bg-slate-50 ring-1 ring-[#091426]')} key={plan}><input checked={draft.plan === plan} className="sr-only" name="plan" onChange={() => update({ plan })} type="radio" /><p className="font-semibold">{plan}</p></label>)}</div></WizardCard><WizardCard icon={PackageCheck} title="Module Selection" description="Các module được lưu để cấp entitlement sau provisioning."><div className="grid gap-3 sm:grid-cols-2">{modules.map((module) => <label className="flex gap-3 rounded-xl border p-4" key={module.key}><input checked={draft.modules.includes(module.key)} onChange={(event) => update({ modules: event.currentTarget.checked ? [...draft.modules, module.key] : draft.modules.filter((key) => key !== module.key) })} type="checkbox" /><span className="font-semibold">{module.name}</span></label>)}</div><Footer back="/platform/tenants/create/step-2" onNext={() => { update({ error: undefined }); location.assign('/platform/tenants/create/step-4'); }} /></WizardCard></div>; }
function DatabaseStep({ draft, update }: Props) { const start = () => { if (!draft.databaseName || !draft.secretRef) return update({ error: 'Thiếu database name hoặc secret reference.' }); update({ error: undefined, provisionState: 'provisioning' }); location.assign('/platform/tenants/create/progress'); }; return <div className="grid gap-6 lg:grid-cols-5"><div className="space-y-6 lg:col-span-3"><div className="flex gap-3 rounded-lg border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900"><Database className="size-4 shrink-0" />Database được tạo tự động trong tenant database cluster.</div><WizardCard icon={Database} title="Database Infrastructure" description="Cấu hình Dedicated Database."><div className="grid gap-5 sm:grid-cols-2"><Field label="Database mode"><div className="flex h-8 items-center gap-2 rounded-lg border bg-slate-100 px-2.5 text-sm text-slate-500"><Lock className="size-3.5" />Dedicated database</div></Field><Field label="Database name"><Input onChange={(event) => update({ databaseName: event.currentTarget.value })} value={draft.databaseName} /></Field><Field label="Host"><Input onChange={(event) => update({ host: event.currentTarget.value })} value={draft.host} /></Field><Field label="Port"><Input onChange={(event) => update({ port: event.currentTarget.value })} type="number" value={draft.port} /></Field><Field label="Secret reference"><Input onChange={(event) => update({ secretRef: event.currentTarget.value })} value={draft.secretRef} /></Field></div><WizardError message={draft.error} /><Footer back="/platform/tenants/create/step-3" nextLabel="Xác nhận & khởi tạo" onNext={start} /></WizardCard></div><SummaryCard draft={draft} /></div>; }
function ProvisioningStep({ draft, update }: Props) { const started = useRef(false); useEffect(() => { if (started.current || draft.provisionState !== 'provisioning') return; started.current = true; const input: CreateTenantRequest = { name: draft.name, slug: draft.slug, admin: { displayName: draft.adminName, email: draft.adminEmail, initialPassword: draft.password }, database: { databaseName: draft.databaseName, host: draft.host, port: Number(draft.port), secretRef: draft.secretRef, ssl: false } }; void fetch('/api/platform/v1/tenants', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json', 'x-csrf-token': csrfToken() }, body: JSON.stringify(input) }).then(async (response) => { if (!response.ok) throw new Error(apiMessage(await response.json().catch(() => ({})))); return response.json() as Promise<CreateTenantResponse>; }).then((response) => update({ provisionState: 'completed', tenantName: response.tenant.name, error: undefined })).catch((cause: unknown) => update({ provisionState: 'failed', error: cause instanceof Error ? cause.message : 'Không thể khởi tạo tenant.' })); }, [draft, update]); const done = draft.provisionState === 'completed'; const failed = draft.provisionState === 'failed'; const labels = ['Tạo Dedicated Database', 'Tạo core_schema và Tenant Admin', 'Ghi nhận Tenant trên Platform']; return <Card className="mx-auto max-w-2xl border-slate-200 shadow-sm"><CardContent className="py-10"><div className="mx-auto grid size-14 place-items-center rounded-full bg-slate-100 text-[#091426]"><ServerCog className={cn('size-7', !done && !failed && 'animate-pulse')} /></div><div className="mt-5 text-center"><h2 className="text-xl font-semibold">{done ? `Đã khởi tạo ${draft.tenantName}` : failed ? 'Không thể khởi tạo Tenant' : `Đang khởi tạo ${draft.name}`}</h2><p className="mt-2 text-sm text-muted-foreground">{done ? 'Tenant và tài khoản quản trị đã sẵn sàng.' : failed ? draft.error : 'Đang tạo database, core schema và tài khoản quản trị.'}</p></div><div className="mt-8 space-y-4">{labels.map((label, index) => <div className="flex items-center gap-3" key={label}><span className={cn('grid size-7 place-items-center rounded-full text-xs', done ? 'bg-[#091426] text-white' : 'bg-slate-100 text-slate-500')}>{done ? <Check className="size-4" /> : index + 1}</span><span className="text-sm">{label}</span><Status state={draft.provisionState} /></div>)}</div><div className="mt-8 flex justify-center">{done ? <Link className="text-sm font-semibold text-[#091426] hover:underline" href={`/t/${draft.slug}/login`} onClick={() => sessionStorage.removeItem(DRAFT_KEY)}>Đến trang đăng nhập Tenant Admin</Link> : <Link className="text-sm font-semibold text-[#091426] hover:underline" href="/platform/tenants">Quay lại danh sách tenant</Link>}</div></CardContent></Card>; }

function WizardCard({ icon: Icon, title, description, children }: { icon: typeof Building2; title: string; description: string; children: React.ReactNode }) { return <Card className="border-slate-200 shadow-sm"><CardHeader className="border-b"><div className="flex items-center gap-2"><Icon className="size-4 text-[#091426]" /><CardTitle>{title}</CardTitle></div><p className="text-sm text-muted-foreground">{description}</p></CardHeader><CardContent className="pt-6">{children}</CardContent></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>; }
function WizardError({ message }: { message?: string }) { return message ? <p className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert">{message}</p> : null; }
function Footer({ back, onNext, nextLabel = 'Tiếp tục' }: { back?: string; onNext: () => void; nextLabel?: string }) { return <div className="mt-8 flex items-center justify-between border-t pt-5">{back ? <Link className="inline-flex h-8 items-center gap-1 rounded-lg border bg-white px-3 text-sm font-medium hover:bg-slate-50" href={back}><ArrowLeft className="size-4" />Quay lại</Link> : <Link className="text-sm text-muted-foreground hover:text-[#091426]" href="/platform/tenants">Hủy</Link>}<Button className="bg-[#091426] hover:bg-[#1e293b]" onClick={onNext}>{nextLabel}<ArrowRight className="size-4" /></Button></div>; }
function SummaryCard({ draft }: { draft: Draft }) { return <Card className="h-fit border-slate-200 shadow-sm lg:col-span-2"><CardHeader><CardTitle>Tóm tắt Tenant</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><Summary label="Doanh nghiệp" value={draft.name || 'Chưa nhập'} /><Summary label="Tenant Admin" value={draft.adminEmail || 'Chưa nhập'} /><Summary label="Gói dịch vụ" value={draft.plan} /><Summary label="Modules" value={draft.modules.join(' · ') || 'Chưa chọn'} /><Summary label="Database" value={draft.databaseName || 'Chưa nhập'} /></CardContent></Card>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function Status({ state }: { state: ProvisionState }) { return <span className={cn('ml-auto rounded-full px-2 py-1 text-xs font-medium', state === 'completed' ? 'bg-emerald-100 text-emerald-800' : state === 'failed' ? 'bg-red-100 text-red-800' : 'bg-slate-200 text-slate-700')}>{state === 'completed' ? 'Hoàn tất' : state === 'failed' ? 'Thất bại' : 'Đang xử lý'}</span>; }
